version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw
      MYSQL_DATABASE: railway
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pas
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
